//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI.DBCS_SERVICE
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DBConnectionString", Namespace = "http://schemas.datacontract.org/2004/07/DBCS_Service.WCF")]
    [System.SerializableAttribute()]
    public partial class DBConnectionString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionStringField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderNameField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionString
        {
            get
            {
                return this.ConnectionStringField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ConnectionStringField, value) != true))
                {
                    this.ConnectionStringField = value;
                    this.RaisePropertyChanged("ConnectionString");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderName
        {
            get
            {
                return this.ProviderNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ProviderNameField, value) != true))
                {
                    this.ProviderNameField = value;
                    this.RaisePropertyChanged("ProviderName");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "DBCS_SERVICE.IWCF_ConnectionInfo")]
    public interface IWCF_ConnectionInfo
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCF_ConnectionInfo/GetDBConnection", ReplyAction = "http://tempuri.org/IWCF_ConnectionInfo/GetDBConnectionResponse")]
        RSI.DBCS_SERVICE.DBConnectionString GetDBConnection(string DBKey);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCF_ConnectionInfo/GetDBConnection", ReplyAction = "http://tempuri.org/IWCF_ConnectionInfo/GetDBConnectionResponse")]
        System.Threading.Tasks.Task<RSI.DBCS_SERVICE.DBConnectionString> GetDBConnectionAsync(string DBKey);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCF_ConnectionInfo/GetDBConnectionArray", ReplyAction = "http://tempuri.org/IWCF_ConnectionInfo/GetDBConnectionArrayResponse")]
        RSI.DBCS_SERVICE.DBConnectionString[] GetDBConnectionArray(string[] DBKey);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCF_ConnectionInfo/GetDBConnectionArray", ReplyAction = "http://tempuri.org/IWCF_ConnectionInfo/GetDBConnectionArrayResponse")]
        System.Threading.Tasks.Task<RSI.DBCS_SERVICE.DBConnectionString[]> GetDBConnectionArrayAsync(string[] DBKey);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCF_ConnectionInfo/GetDBCSCodeBySystemId", ReplyAction = "http://tempuri.org/IWCF_ConnectionInfo/GetDBCSCodeBySystemIdResponse")]
        System.Data.DataSet GetDBCSCodeBySystemId(int SystemId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCF_ConnectionInfo/GetDBCSCodeBySystemId", ReplyAction = "http://tempuri.org/IWCF_ConnectionInfo/GetDBCSCodeBySystemIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDBCSCodeBySystemIdAsync(int SystemId);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCF_ConnectionInfoChannel : RSI.DBCS_SERVICE.IWCF_ConnectionInfo, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCF_ConnectionInfoClient : System.ServiceModel.ClientBase<RSI.DBCS_SERVICE.IWCF_ConnectionInfo>, RSI.DBCS_SERVICE.IWCF_ConnectionInfo
    {

        public WCF_ConnectionInfoClient()
        {
        }

        public WCF_ConnectionInfoClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public WCF_ConnectionInfoClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCF_ConnectionInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCF_ConnectionInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public RSI.DBCS_SERVICE.DBConnectionString GetDBConnection(string DBKey)
        {
            return base.Channel.GetDBConnection(DBKey);
        }

        public System.Threading.Tasks.Task<RSI.DBCS_SERVICE.DBConnectionString> GetDBConnectionAsync(string DBKey)
        {
            return base.Channel.GetDBConnectionAsync(DBKey);
        }

        public RSI.DBCS_SERVICE.DBConnectionString[] GetDBConnectionArray(string[] DBKey)
        {
            return base.Channel.GetDBConnectionArray(DBKey);
        }

        public System.Threading.Tasks.Task<RSI.DBCS_SERVICE.DBConnectionString[]> GetDBConnectionArrayAsync(string[] DBKey)
        {
            return base.Channel.GetDBConnectionArrayAsync(DBKey);
        }

        public System.Data.DataSet GetDBCSCodeBySystemId(int SystemId)
        {
            return base.Channel.GetDBCSCodeBySystemId(SystemId);
        }

        public System.Threading.Tasks.Task<System.Data.DataSet> GetDBCSCodeBySystemIdAsync(int SystemId)
        {
            return base.Channel.GetDBCSCodeBySystemIdAsync(SystemId);
        }
    }
}
