//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI.IDS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDS.MailSoap")]
    public interface MailSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResendMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ResendMail(string strSentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ResendMailAsync(string strSentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RunJob(string strCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunJob", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RunJobAsync(string strCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CallSend(string strCode, string strMailCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallSend", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CallSendAsync(string strCode, string strMailCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDDRSQLQueryResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDDRSQLQueryResult(string strCode, string strDBCSCode, string strDatabase, string strSQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDDRSQLQueryResult", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDDRSQLQueryResultAsync(string strCode, string strDBCSCode, string strDatabase, string strSQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecipientDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRecipientDetail(string strCode, string strMailCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecipientDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRecipientDetailAsync(string strCode, string strMailCode);
        
        // CODEGEN: 參數 'intCompassSystemID' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailSentLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RSI.IDS.GetMailSentLogResponse GetMailSentLog(RSI.IDS.GetMailSentLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailSentLog", ReplyAction="*")]
        System.Threading.Tasks.Task<RSI.IDS.GetMailSentLogResponse> GetMailSentLogAsync(RSI.IDS.GetMailSentLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_00", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_00(string strMailCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_00", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_00Async(string strMailCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_04", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_04(string strMailCode, string strBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_04", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_04Async(string strMailCode, string strBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_06", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_06(string strMailCode, string strSubject, string strBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_06", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_06Async(string strMailCode, string strSubject, string strBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_07", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_07(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_07", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_07Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_07A", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_07A(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strUrl, bool bolGrabImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_07A", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_07AAsync(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strUrl, bool bolGrabImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_08", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_08(string strMailCode, string strFormUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_08", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_08Async(string strMailCode, string strFormUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_08A", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_08A(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strUrl, bool bolGrabImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_08A", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_08AAsync(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strUrl, bool bolGrabImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_15", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_15(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_15", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_15Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_23", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_23(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileDirectoryPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_23", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_23Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileDirectoryPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_31", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_31(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileDirectoryPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_31", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_31Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileDirectoryPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_39", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_39(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileBase64String);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_39", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_39Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileBase64String);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_40", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_40(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileBase64String);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_40", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_40Async(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileBase64String);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_47", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_47(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileBase64String);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_47", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_47Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileBase64String);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_48", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_48(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileBase64String);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_48", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_48Async(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileBase64String);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_57", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_57(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFLMCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_57", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_57Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFLMCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_58", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_58(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFLMCode, RSI.IDS.PDFSetting _PDFSetting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_58", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_58Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFLMCode, RSI.IDS.PDFSetting _PDFSetting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_59", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_59(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFLMCode, RSI.IDS.PDFSetting _PDFSetting, RSI.IDS.PDFWatermarkSetting _PDFWatermarkSetting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_59", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_59Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFLMCode, RSI.IDS.PDFSetting _PDFSetting, RSI.IDS.PDFWatermarkSetting _PDFWatermarkSetting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_60", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_60(string strMailCode, string strFormUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFLMCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_60", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_60Async(string strMailCode, string strFormUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFLMCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_07ALJ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ManualSend_07ALJ(string strMailCode, string strRecipients, string strCopyRecipients, string strBlindCopyRecipients, string strSubject, string strUrl, bool bolGrabImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualSend_07ALJ", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ManualSend_07ALJAsync(string strMailCode, string strRecipients, string strCopyRecipients, string strBlindCopyRecipients, string strSubject, string strUrl, bool bolGrabImage);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMailSentLog", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMailSentLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime dtmStartDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime dtmEndDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> intCompassSystemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> intMailID;
        
        public GetMailSentLogRequest() {
        }
        
        public GetMailSentLogRequest(System.DateTime dtmStartDate, System.DateTime dtmEndDate, System.Nullable<int> intCompassSystemID, System.Nullable<int> intMailID) {
            this.dtmStartDate = dtmStartDate;
            this.dtmEndDate = dtmEndDate;
            this.intCompassSystemID = intCompassSystemID;
            this.intMailID = intMailID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMailSentLogResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMailSentLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetMailSentLogResult;
        
        public GetMailSentLogResponse() {
        }
        
        public GetMailSentLogResponse(System.Data.DataSet GetMailSentLogResult) {
            this.GetMailSentLogResult = GetMailSentLogResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PDFSetting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool addWatermarkField;
        
        private bool addDownloadInfoField;
        
        private string customDownloadInfoField;
        
        private string viewPasswordField;
        
        private bool allowHandleField;
        
        private bool allowPrintField;
        
        private bool allowCopyField;
        
        private bool allowModifyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AddWatermark {
            get {
                return this.addWatermarkField;
            }
            set {
                this.addWatermarkField = value;
                this.RaisePropertyChanged("AddWatermark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool AddDownloadInfo {
            get {
                return this.addDownloadInfoField;
            }
            set {
                this.addDownloadInfoField = value;
                this.RaisePropertyChanged("AddDownloadInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomDownloadInfo {
            get {
                return this.customDownloadInfoField;
            }
            set {
                this.customDownloadInfoField = value;
                this.RaisePropertyChanged("CustomDownloadInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ViewPassword {
            get {
                return this.viewPasswordField;
            }
            set {
                this.viewPasswordField = value;
                this.RaisePropertyChanged("ViewPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool AllowHandle {
            get {
                return this.allowHandleField;
            }
            set {
                this.allowHandleField = value;
                this.RaisePropertyChanged("AllowHandle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool AllowPrint {
            get {
                return this.allowPrintField;
            }
            set {
                this.allowPrintField = value;
                this.RaisePropertyChanged("AllowPrint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool AllowCopy {
            get {
                return this.allowCopyField;
            }
            set {
                this.allowCopyField = value;
                this.RaisePropertyChanged("AllowCopy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool AllowModify {
            get {
                return this.allowModifyField;
            }
            set {
                this.allowModifyField = value;
                this.RaisePropertyChanged("AllowModify");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PDFWatermarkSetting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentField;
        
        private int fontSizeField;
        
        private string fontColorHtmlField;
        
        private float fontLocationXField;
        
        private float fontLocationYField;
        
        private float rotationField;
        
        private float fontTransparencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
                this.RaisePropertyChanged("FontSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FontColorHtml {
            get {
                return this.fontColorHtmlField;
            }
            set {
                this.fontColorHtmlField = value;
                this.RaisePropertyChanged("FontColorHtml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float FontLocationX {
            get {
                return this.fontLocationXField;
            }
            set {
                this.fontLocationXField = value;
                this.RaisePropertyChanged("FontLocationX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float FontLocationY {
            get {
                return this.fontLocationYField;
            }
            set {
                this.fontLocationYField = value;
                this.RaisePropertyChanged("FontLocationY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float Rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
                this.RaisePropertyChanged("Rotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float FontTransparency {
            get {
                return this.fontTransparencyField;
            }
            set {
                this.fontTransparencyField = value;
                this.RaisePropertyChanged("FontTransparency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailSoapChannel : RSI.IDS.MailSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailSoapClient : System.ServiceModel.ClientBase<RSI.IDS.MailSoap>, RSI.IDS.MailSoap {
        
        public MailSoapClient() {
        }
        
        public MailSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ResendMail(string strSentCode) {
            return base.Channel.ResendMail(strSentCode);
        }
        
        public System.Threading.Tasks.Task<bool> ResendMailAsync(string strSentCode) {
            return base.Channel.ResendMailAsync(strSentCode);
        }
        
        public bool RunJob(string strCode) {
            return base.Channel.RunJob(strCode);
        }
        
        public System.Threading.Tasks.Task<bool> RunJobAsync(string strCode) {
            return base.Channel.RunJobAsync(strCode);
        }
        
        public bool CallSend(string strCode, string strMailCode) {
            return base.Channel.CallSend(strCode, strMailCode);
        }
        
        public System.Threading.Tasks.Task<bool> CallSendAsync(string strCode, string strMailCode) {
            return base.Channel.CallSendAsync(strCode, strMailCode);
        }
        
        public System.Data.DataSet GetDDRSQLQueryResult(string strCode, string strDBCSCode, string strDatabase, string strSQL) {
            return base.Channel.GetDDRSQLQueryResult(strCode, strDBCSCode, strDatabase, strSQL);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDDRSQLQueryResultAsync(string strCode, string strDBCSCode, string strDatabase, string strSQL) {
            return base.Channel.GetDDRSQLQueryResultAsync(strCode, strDBCSCode, strDatabase, strSQL);
        }
        
        public System.Data.DataTable GetRecipientDetail(string strCode, string strMailCode) {
            return base.Channel.GetRecipientDetail(strCode, strMailCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRecipientDetailAsync(string strCode, string strMailCode) {
            return base.Channel.GetRecipientDetailAsync(strCode, strMailCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI.IDS.GetMailSentLogResponse RSI.IDS.MailSoap.GetMailSentLog(RSI.IDS.GetMailSentLogRequest request) {
            return base.Channel.GetMailSentLog(request);
        }
        
        public System.Data.DataSet GetMailSentLog(System.DateTime dtmStartDate, System.DateTime dtmEndDate, System.Nullable<int> intCompassSystemID, System.Nullable<int> intMailID) {
            RSI.IDS.GetMailSentLogRequest inValue = new RSI.IDS.GetMailSentLogRequest();
            inValue.dtmStartDate = dtmStartDate;
            inValue.dtmEndDate = dtmEndDate;
            inValue.intCompassSystemID = intCompassSystemID;
            inValue.intMailID = intMailID;
            RSI.IDS.GetMailSentLogResponse retVal = ((RSI.IDS.MailSoap)(this)).GetMailSentLog(inValue);
            return retVal.GetMailSentLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI.IDS.GetMailSentLogResponse> RSI.IDS.MailSoap.GetMailSentLogAsync(RSI.IDS.GetMailSentLogRequest request) {
            return base.Channel.GetMailSentLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI.IDS.GetMailSentLogResponse> GetMailSentLogAsync(System.DateTime dtmStartDate, System.DateTime dtmEndDate, System.Nullable<int> intCompassSystemID, System.Nullable<int> intMailID) {
            RSI.IDS.GetMailSentLogRequest inValue = new RSI.IDS.GetMailSentLogRequest();
            inValue.dtmStartDate = dtmStartDate;
            inValue.dtmEndDate = dtmEndDate;
            inValue.intCompassSystemID = intCompassSystemID;
            inValue.intMailID = intMailID;
            return ((RSI.IDS.MailSoap)(this)).GetMailSentLogAsync(inValue);
        }
        
        public bool ManualSend_00(string strMailCode) {
            return base.Channel.ManualSend_00(strMailCode);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_00Async(string strMailCode) {
            return base.Channel.ManualSend_00Async(strMailCode);
        }
        
        public bool ManualSend_04(string strMailCode, string strBody) {
            return base.Channel.ManualSend_04(strMailCode, strBody);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_04Async(string strMailCode, string strBody) {
            return base.Channel.ManualSend_04Async(strMailCode, strBody);
        }
        
        public bool ManualSend_06(string strMailCode, string strSubject, string strBody) {
            return base.Channel.ManualSend_06(strMailCode, strSubject, strBody);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_06Async(string strMailCode, string strSubject, string strBody) {
            return base.Channel.ManualSend_06Async(strMailCode, strSubject, strBody);
        }
        
        public bool ManualSend_07(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody) {
            return base.Channel.ManualSend_07(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_07Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody) {
            return base.Channel.ManualSend_07Async(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody);
        }
        
        public bool ManualSend_07A(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strUrl, bool bolGrabImage) {
            return base.Channel.ManualSend_07A(strMailCode, strRecipients, strCopyRecipients, strSubject, strUrl, bolGrabImage);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_07AAsync(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strUrl, bool bolGrabImage) {
            return base.Channel.ManualSend_07AAsync(strMailCode, strRecipients, strCopyRecipients, strSubject, strUrl, bolGrabImage);
        }
        
        public bool ManualSend_08(string strMailCode, string strFormUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody) {
            return base.Channel.ManualSend_08(strMailCode, strFormUser, strRecipients, strCopyRecipients, strSubject, strBody);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_08Async(string strMailCode, string strFormUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody) {
            return base.Channel.ManualSend_08Async(strMailCode, strFormUser, strRecipients, strCopyRecipients, strSubject, strBody);
        }
        
        public bool ManualSend_08A(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strUrl, bool bolGrabImage) {
            return base.Channel.ManualSend_08A(strMailCode, strFromUser, strRecipients, strCopyRecipients, strSubject, strUrl, bolGrabImage);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_08AAsync(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strUrl, bool bolGrabImage) {
            return base.Channel.ManualSend_08AAsync(strMailCode, strFromUser, strRecipients, strCopyRecipients, strSubject, strUrl, bolGrabImage);
        }
        
        public bool ManualSend_15(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance) {
            return base.Channel.ManualSend_15(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strImportance);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_15Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance) {
            return base.Channel.ManualSend_15Async(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strImportance);
        }
        
        public bool ManualSend_23(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileDirectoryPath) {
            return base.Channel.ManualSend_23(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strFileDirectoryPath);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_23Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileDirectoryPath) {
            return base.Channel.ManualSend_23Async(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strFileDirectoryPath);
        }
        
        public bool ManualSend_31(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileDirectoryPath) {
            return base.Channel.ManualSend_31(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFileDirectoryPath);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_31Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileDirectoryPath) {
            return base.Channel.ManualSend_31Async(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFileDirectoryPath);
        }
        
        public bool ManualSend_39(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileBase64String) {
            return base.Channel.ManualSend_39(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strFileBase64String);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_39Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileBase64String) {
            return base.Channel.ManualSend_39Async(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strFileBase64String);
        }
        
        public bool ManualSend_40(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileBase64String) {
            return base.Channel.ManualSend_40(strMailCode, strFromUser, strRecipients, strCopyRecipients, strSubject, strBody, strFileBase64String);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_40Async(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFileBase64String) {
            return base.Channel.ManualSend_40Async(strMailCode, strFromUser, strRecipients, strCopyRecipients, strSubject, strBody, strFileBase64String);
        }
        
        public bool ManualSend_47(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileBase64String) {
            return base.Channel.ManualSend_47(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFileBase64String);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_47Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileBase64String) {
            return base.Channel.ManualSend_47Async(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFileBase64String);
        }
        
        public bool ManualSend_48(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileBase64String) {
            return base.Channel.ManualSend_48(strMailCode, strFromUser, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFileBase64String);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_48Async(string strMailCode, string strFromUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFileBase64String) {
            return base.Channel.ManualSend_48Async(strMailCode, strFromUser, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFileBase64String);
        }
        
        public bool ManualSend_57(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFLMCode) {
            return base.Channel.ManualSend_57(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFLMCode);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_57Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFLMCode) {
            return base.Channel.ManualSend_57Async(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFLMCode);
        }
        
        public bool ManualSend_58(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFLMCode, RSI.IDS.PDFSetting _PDFSetting) {
            return base.Channel.ManualSend_58(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strFLMCode, _PDFSetting);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_58Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFLMCode, RSI.IDS.PDFSetting _PDFSetting) {
            return base.Channel.ManualSend_58Async(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strFLMCode, _PDFSetting);
        }
        
        public bool ManualSend_59(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFLMCode, RSI.IDS.PDFSetting _PDFSetting, RSI.IDS.PDFWatermarkSetting _PDFWatermarkSetting) {
            return base.Channel.ManualSend_59(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strFLMCode, _PDFSetting, _PDFWatermarkSetting);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_59Async(string strMailCode, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strFLMCode, RSI.IDS.PDFSetting _PDFSetting, RSI.IDS.PDFWatermarkSetting _PDFWatermarkSetting) {
            return base.Channel.ManualSend_59Async(strMailCode, strRecipients, strCopyRecipients, strSubject, strBody, strFLMCode, _PDFSetting, _PDFWatermarkSetting);
        }
        
        public bool ManualSend_60(string strMailCode, string strFormUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFLMCode) {
            return base.Channel.ManualSend_60(strMailCode, strFormUser, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFLMCode);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_60Async(string strMailCode, string strFormUser, string strRecipients, string strCopyRecipients, string strSubject, string strBody, string strImportance, string strFLMCode) {
            return base.Channel.ManualSend_60Async(strMailCode, strFormUser, strRecipients, strCopyRecipients, strSubject, strBody, strImportance, strFLMCode);
        }
        
        public bool ManualSend_07ALJ(string strMailCode, string strRecipients, string strCopyRecipients, string strBlindCopyRecipients, string strSubject, string strUrl, bool bolGrabImage) {
            return base.Channel.ManualSend_07ALJ(strMailCode, strRecipients, strCopyRecipients, strBlindCopyRecipients, strSubject, strUrl, bolGrabImage);
        }
        
        public System.Threading.Tasks.Task<bool> ManualSend_07ALJAsync(string strMailCode, string strRecipients, string strCopyRecipients, string strBlindCopyRecipients, string strSubject, string strUrl, bool bolGrabImage) {
            return base.Channel.ManualSend_07ALJAsync(strMailCode, strRecipients, strCopyRecipients, strBlindCopyRecipients, strSubject, strUrl, bolGrabImage);
        }
    }
}
